config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :apple_musics
  resources :line_musics
  resources :d_anime_stores
  resources :au_video_passes
  resources :fods
  resources :d_tvs
  resources :netflixes
  resources :you_tube_premia
  resources :spotifies
  resources :unexts
  resources :play_station_networks
  resources :google_play_musics
  resources :amazon_kindle_unlimiteds
  resources :amazon_musics
  resources :amazon_primes
  devise_for :users
  root 'tops#index'
  resources :hulus
  resources :googles
  resources :amazons

  get '/tops', to: 'tops#index'
  get '/second', to: 'tops#second'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/amazon_music.rb
# frozen_string_literal: true

class AmazonMusic < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/amazon_prime.rb
# frozen_string_literal: true

class AmazonPrime < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/apple_music.rb
# frozen_string_literal: true

class AppleMusic < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/au_video_pass.rb
# frozen_string_literal: true

class AuVideoPass < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/d_anime_store.rb
# frozen_string_literal: true

class DAnimeStore < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/d_tv.rb
# frozen_string_literal: true

class DTv < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/fod.rb
# frozen_string_literal: true

class Fod < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/hulu.rb
# frozen_string_literal: true

class Hulu < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/line_music.rb
# frozen_string_literal: true

class LineMusic < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/netflix.rb
# frozen_string_literal: true

class Netflix < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/spotify.rb
# frozen_string_literal: true

class Spotify < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/unext.rb
# frozen_string_literal: true

class Unext < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :amazon_kindle_unlimiteds
  has_many :amazon_musics
  has_many :amazon_primes
  has_many :google_play_musics
  has_many :hulus
  has_many :play_station_networks
  has_many :spotifies
  has_many :unexts
  has_many :apple_musics
  has_many :d_anime_stores
  has_many :au_video_passes
  has_many :d_tvs
  has_many :fods
  has_many :line_musics
  has_many :netflixes
  has_many :you_tube_premia
end

app/controllers/au_video_passes_controller.rb
# frozen_string_literal: true

class AuVideoPassesController < ApplicationController
  before_action :set_au_video_pass, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /au_video_passes
  # GET /au_video_passes.json
  def index
    @au_video_passes = AuVideoPass.all
  end

  # GET /au_video_passes/1
  # GET /au_video_passes/1.json
  def show; end

  # GET /au_video_passes/new
  def new
    @au_video_pass = current_user.au_video_passes.build
  end

  # GET /au_video_passes/1/edit
  def edit; end

  # POST /au_video_passes
  # POST /au_video_passes.json
  def create
    @au_video_pass = current_user.au_video_passes.build(au_video_pass_params)

    respond_to do |format|
      if @au_video_pass.save
        format.html { redirect_to root_path, notice: success('auビデオパス') }
        format.json { render :show, status: :created, location: @au_video_pass }
      else
        format.html { render :new }
        format.json { render json: @au_video_pass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /au_video_passes/1
  # PATCH/PUT /au_video_passes/1.json
  def update
    respond_to do |format|
      if @au_video_pass.update(au_video_pass_params)
        format.html { redirect_to root_path, notice: update('auビデオパス') }
        format.json { render :show, status: :ok, location: @au_video_pass }
      else
        format.html { render :edit }
        format.json { render json: @au_video_pass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /au_video_passes/1
  # DELETE /au_video_passes/1.json
  def destroy
    @au_video_pass.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: delete('auビデオパス') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_au_video_pass
    @au_video_pass = AuVideoPass.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def au_video_pass_params
    params.require(:au_video_pass).permit(:price, :date, :update_period, :status, :memo, :user_id)
  end
end

app/helpers/amazons_helper.rb
# frozen_string_literal: true

module AmazonsHelper
end

app/helpers/au_video_passes_helper.rb
# frozen_string_literal: true

module AuVideoPassesHelper
end

app/helpers/d_t_vs_helper.rb
# frozen_string_literal: true

module DTVsHelper
end

app/helpers/fo_ds_helper.rb
# frozen_string_literal: true

module FoDsHelper
end

app/helpers/googoles_helper.rb
# frozen_string_literal: true

module GoogolesHelper
end

app/helpers/hulus_helper.rb
# frozen_string_literal: true

module HulusHelper
end

app/helpers/top_helper.rb
# frozen_string_literal: true

module TopHelper
end

app/helpers/unexts_helper.rb
# frozen_string_literal: true

module UnextsHelper
end

app/views/au_video_passes/_form.html.erb
<%= form_with(model: au_video_pass, local: true) do |form| %>
  <% if au_video_pass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(au_video_pass.errors.count, "error") %> prohibited this au_video_pass from being saved:</h2>

      <ul>
      <% au_video_pass.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :update_period %>
    <%= form.number_field :update_period %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_area :memo %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/au_video_passes/edit.html.erb
<h1>Editing Au Video Pass</h1>

<%= render 'form', au_video_pass: @au_video_pass %>

<%= link_to 'Show', @au_video_pass %> |
<%= link_to 'Back', au_video_passes_path %>

app/views/au_video_passes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Au Video Passes</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Date</th>
      <th>Update period</th>
      <th>Status</th>
      <th>Memo</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @au_video_passes.each do |au_video_pass| %>
      <tr>
        <td><%= au_video_pass.price %></td>
        <td><%= au_video_pass.date %></td>
        <td><%= au_video_pass.update_period %></td>
        <td><%= au_video_pass.status %></td>
        <td><%= au_video_pass.memo %></td>
        <td><%= au_video_pass.user_id %></td>
        <td><%= link_to 'Show', au_video_pass %></td>
        <td><%= link_to 'Edit', edit_au_video_pass_path(au_video_pass) %></td>
        <td><%= link_to 'Destroy', au_video_pass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Au Video Pass', new_au_video_pass_path %>

app/views/au_video_passes/new.html.erb
<h1>auビデオパス</h1>
<%= render 'layouts/alert', service: @au_video_pass %>
<%= render 'layouts/form', service: @au_video_pass %>

app/views/au_video_passes/show.html.erb
<%= render 'layouts/show', name: 'auビデオパス', url: @au_video_pass %>