config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :apple_musics
  resources :line_musics
  resources :d_anime_stores
  resources :au_video_passes
  resources :fods
  resources :d_tvs
  resources :netflixes
  resources :you_tube_premia
  resources :spotifies
  resources :unexts
  resources :play_station_networks
  resources :google_play_musics
  resources :amazon_kindle_unlimiteds
  resources :amazon_musics
  resources :amazon_primes
  devise_for :users
  root 'tops#index'
  resources :hulus
  resources :googles
  resources :amazons

  get '/tops', to: 'tops#index'
  get '/second', to: 'tops#second'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/amazon_music.rb
# frozen_string_literal: true

class AmazonMusic < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/amazon_prime.rb
# frozen_string_literal: true

class AmazonPrime < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/apple_music.rb
# frozen_string_literal: true

class AppleMusic < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/au_video_pass.rb
# frozen_string_literal: true

class AuVideoPass < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/d_anime_store.rb
# frozen_string_literal: true

class DAnimeStore < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/d_tv.rb
# frozen_string_literal: true

class DTv < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/fod.rb
# frozen_string_literal: true

class Fod < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/hulu.rb
# frozen_string_literal: true

class Hulu < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/line_music.rb
# frozen_string_literal: true

class LineMusic < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/netflix.rb
# frozen_string_literal: true

class Netflix < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/spotify.rb
# frozen_string_literal: true

class Spotify < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/unext.rb
# frozen_string_literal: true

class Unext < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :amazon_kindle_unlimiteds
  has_many :amazon_musics
  has_many :amazon_primes
  has_many :google_play_musics
  has_many :hulus
  has_many :play_station_networks
  has_many :spotifies
  has_many :unexts
  has_many :apple_musics
  has_many :d_anime_stores
  has_many :au_video_passes
  has_many :d_tvs
  has_many :fods
  has_many :line_musics
  has_many :netflixes
  has_many :you_tube_premia
end

app/models/you_tube_premium.rb
# frozen_string_literal: true

class YouTubePremium < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/controllers/d_anime_stores_controller.rb
# frozen_string_literal: true

class DAnimeStoresController < ApplicationController
  before_action :set_d_anime_store, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /d_anime_stores
  # GET /d_anime_stores.json
  def index
    @d_anime_stores = DAnimeStore.all
  end

  # GET /d_anime_stores/1
  # GET /d_anime_stores/1.json
  def show; end

  # GET /d_anime_stores/new
  def new
    @d_anime_store = current_user.d_anime_stores.build
  end

  # GET /d_anime_stores/1/edit
  def edit; end

  # POST /d_anime_stores
  # POST /d_anime_stores.json
  def create
    @d_anime_store = current_user.d_anime_stores.build(d_anime_store_params)

    respond_to do |format|
      if @d_anime_store.save
        format.html { redirect_to root_path, notice: success('dアニメストア') }
        format.json { render :show, status: :created, location: @d_anime_store }
      else
        format.html { render :new }
        format.json { render json: @d_anime_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /d_anime_stores/1
  # PATCH/PUT /d_anime_stores/1.json
  def update
    respond_to do |format|
      if @d_anime_store.update(d_anime_store_params)
        format.html { redirect_to root_path, notice: update('dアニメストア') }
        format.json { render :show, status: :ok, location: @d_anime_store }
      else
        format.html { render :edit }
        format.json { render json: @d_anime_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /d_anime_stores/1
  # DELETE /d_anime_stores/1.json
  def destroy
    @d_anime_store.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: delete('dアニメストア') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_d_anime_store
    @d_anime_store = DAnimeStore.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def d_anime_store_params
    params.require(:d_anime_store).permit(:price, :date, :update_period, :status, :memo, :user_id)
  end
end

app/helpers/amazons_helper.rb
# frozen_string_literal: true

module AmazonsHelper
end

app/helpers/d_anime_stores_helper.rb
# frozen_string_literal: true

module DAnimeStoresHelper
end

app/helpers/d_t_vs_helper.rb
# frozen_string_literal: true

module DTVsHelper
end

app/helpers/fo_ds_helper.rb
# frozen_string_literal: true

module FoDsHelper
end

app/helpers/googoles_helper.rb
# frozen_string_literal: true

module GoogolesHelper
end

app/helpers/hulus_helper.rb
# frozen_string_literal: true

module HulusHelper
end

app/helpers/top_helper.rb
# frozen_string_literal: true

module TopHelper
end

app/helpers/unexts_helper.rb
# frozen_string_literal: true

module UnextsHelper
end

app/views/d_anime_stores/_form.html.erb
<%= form_with(model: d_anime_store, local: true) do |form| %>
  <% if d_anime_store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(d_anime_store.errors.count, "error") %> prohibited this d_anime_store from being saved:</h2>

      <ul>
      <% d_anime_store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :update_period %>
    <%= form.number_field :update_period %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_area :memo %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/d_anime_stores/edit.html.erb
<h1>Editing D Anime Store</h1>

<%= render 'form', d_anime_store: @d_anime_store %>

<%= link_to 'Show', @d_anime_store %> |
<%= link_to 'Back', d_anime_stores_path %>

app/views/d_anime_stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>D Anime Stores</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Date</th>
      <th>Update period</th>
      <th>Status</th>
      <th>Memo</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @d_anime_stores.each do |d_anime_store| %>
      <tr>
        <td><%= d_anime_store.price %></td>
        <td><%= d_anime_store.date %></td>
        <td><%= d_anime_store.update_period %></td>
        <td><%= d_anime_store.status %></td>
        <td><%= d_anime_store.memo %></td>
        <td><%= d_anime_store.user_id %></td>
        <td><%= link_to 'Show', d_anime_store %></td>
        <td><%= link_to 'Edit', edit_d_anime_store_path(d_anime_store) %></td>
        <td><%= link_to 'Destroy', d_anime_store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New D Anime Store', new_d_anime_store_path %>

app/views/d_anime_stores/new.html.erb
<h1>dアニメストア</h1>
<%= render 'layouts/alert', service: @d_anime_store %>
<%= render 'layouts/form', service: @d_anime_store %>

app/views/d_anime_stores/show.html.erb
<%= render 'layouts/show', name: 'Dアニメストア', url: @d_anime_store %>