config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :apple_musics
  resources :line_musics
  resources :d_anime_stores
  resources :au_video_passes
  resources :fods
  resources :d_tvs
  resources :netflixes
  resources :you_tube_premia
  resources :spotifies
  resources :unexts
  resources :play_station_networks
  resources :google_play_musics
  resources :amazon_kindle_unlimiteds
  resources :amazon_musics
  resources :amazon_primes
  devise_for :users
  root 'tops#index'
  resources :hulus
  resources :googles
  resources :amazons

  get '/tops', to: 'tops#index'
  get '/second', to: 'tops#second'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/amazon_music.rb
# frozen_string_literal: true

class AmazonMusic < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/amazon_prime.rb
# frozen_string_literal: true

class AmazonPrime < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/apple_music.rb
# frozen_string_literal: true

class AppleMusic < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/au_video_pass.rb
# frozen_string_literal: true

class AuVideoPass < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/d_anime_store.rb
# frozen_string_literal: true

class DAnimeStore < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/d_tv.rb
# frozen_string_literal: true

class DTv < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/fod.rb
# frozen_string_literal: true

class Fod < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/hulu.rb
# frozen_string_literal: true

class Hulu < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/line_music.rb
# frozen_string_literal: true

class LineMusic < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/netflix.rb
# frozen_string_literal: true

class Netflix < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/spotify.rb
# frozen_string_literal: true

class Spotify < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/unext.rb
# frozen_string_literal: true

class Unext < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :amazon_kindle_unlimiteds
  has_many :amazon_musics
  has_many :amazon_primes
  has_many :google_play_musics
  has_many :hulus
  has_many :play_station_networks
  has_many :spotifies
  has_many :unexts
  has_many :apple_musics
  has_many :d_anime_stores
  has_many :au_video_passes
  has_many :d_tvs
  has_many :fods
  has_many :line_musics
  has_many :netflixes
  has_many :you_tube_premia
end

app/models/you_tube_premium.rb
# frozen_string_literal: true

class YouTubePremium < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/controllers/unexts_controller.rb
# frozen_string_literal: true

class UnextsController < ApplicationController
  before_action :set_unext, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /unexts
  # GET /unexts.json
  def index
    @unexts = Unext.all
  end

  # GET /unexts/1
  # GET /unexts/1.json
  def show; end

  # GET /unexts/new
  def new
    @unext = current_user.unexts.build
  end

  # GET /unexts/1/edit
  def edit; end

  # POST /unexts
  # POST /unexts.json
  def create
    @unext = current_user.unexts.build(unext_params)

    respond_to do |format|
      if @unext.save
        format.html { redirect_to root_path, notice: success('U-NEXT') }
        format.json { render :show, status: :created, location: @unext }
      else
        format.html { render :new }
        format.json { render json: @unext.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unexts/1
  # PATCH/PUT /unexts/1.json
  def update
    respond_to do |format|
      if @unext.update(unext_params)
        format.html { redirect_to root_path, notice: update('U-NEXT') }
        format.json { render :show, status: :ok, location: @unext }
      else
        format.html { render :edit }
        format.json { render json: @unext.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unexts/1
  # DELETE /unexts/1.json
  def destroy
    @unext.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: delete('U-NEXT') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_unext
    @unext = Unext.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def unext_params
    params.require(:unext).permit(:price, :issue_date, :update_period, :status, :memo)
  end
end

app/helpers/amazons_helper.rb
# frozen_string_literal: true

module AmazonsHelper
end

app/helpers/d_t_vs_helper.rb
# frozen_string_literal: true

module DTVsHelper
end

app/helpers/fo_ds_helper.rb
# frozen_string_literal: true

module FoDsHelper
end

app/helpers/googoles_helper.rb
# frozen_string_literal: true

module GoogolesHelper
end

app/helpers/hulus_helper.rb
# frozen_string_literal: true

module HulusHelper
end

app/helpers/netflixes_helper.rb
# frozen_string_literal: true

module NetflixesHelper
end

app/helpers/top_helper.rb
# frozen_string_literal: true

module TopHelper
end

app/helpers/unexts_helper.rb
# frozen_string_literal: true

module UnextsHelper
end

app/views/unexts/_form.html.erb
<%= form_with(model: unext, local: true) do |form| %>
  <% if unext.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unext.errors.count, "error") %> prohibited this unext from being saved:</h2>

      <ul>
      <% unext.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :issue_date %>
    <%= form.date_select :issue_date %>
  </div>

  <div class="field">
    <%= form.label :update_period %>
    <%= form.number_field :update_period %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_area :memo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/unexts/edit.html.erb
<h1>Editing Unext</h1>

<%= render 'form', unext: @unext %>

<%= link_to 'Show', @unext %> |
<%= link_to 'Back', unexts_path %>

app/views/unexts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Unexts</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Issue date</th>
      <th>Update period</th>
      <th>Status</th>
      <th>Memo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unexts.each do |unext| %>
      <tr>
        <td><%= unext.price %></td>
        <td><%= unext.issue_date %></td>
        <td><%= unext.update_period %></td>
        <td><%= unext.status %></td>
        <td><%= unext.memo %></td>
        <td><%= link_to 'Show', unext %></td>
        <td><%= link_to 'Edit', edit_unext_path(unext) %></td>
        <td><%= link_to 'Destroy', unext, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unext', new_unext_path %>

app/views/unexts/new.html.erb
<h1>U-NEXT</h1>
<%= render 'layouts/alert', service: @unext %>
<%= render 'layouts/form', service: @unext %>

app/views/unexts/show.html.erb
<%= render 'layouts/show', name: 'U-NEXT', url: @unext %>