config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :apple_musics
  resources :line_musics
  resources :d_anime_stores
  resources :au_video_passes
  resources :fods
  resources :d_tvs
  resources :netflixes
  resources :you_tube_premia
  resources :spotifies
  resources :unexts
  resources :play_station_networks
  resources :google_play_musics
  resources :amazon_kindle_unlimiteds
  resources :amazon_musics
  resources :amazon_primes
  devise_for :users
  root 'tops#index'
  resources :hulus
  resources :googles
  resources :amazons

  get '/tops', to: 'tops#index'
  get '/second', to: 'tops#second'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/amazon_music.rb
# frozen_string_literal: true

class AmazonMusic < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/amazon_prime.rb
# frozen_string_literal: true

class AmazonPrime < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/apple_music.rb
# frozen_string_literal: true

class AppleMusic < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/au_video_pass.rb
# frozen_string_literal: true

class AuVideoPass < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/d_anime_store.rb
# frozen_string_literal: true

class DAnimeStore < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/d_tv.rb
# frozen_string_literal: true

class DTv < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/fod.rb
# frozen_string_literal: true

class Fod < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/hulu.rb
# frozen_string_literal: true

class Hulu < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/line_music.rb
# frozen_string_literal: true

class LineMusic < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/netflix.rb
# frozen_string_literal: true

class Netflix < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/spotify.rb
# frozen_string_literal: true

class Spotify < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/unext.rb
# frozen_string_literal: true

class Unext < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :amazon_kindle_unlimiteds
  has_many :amazon_musics
  has_many :amazon_primes
  has_many :google_play_musics
  has_many :hulus
  has_many :play_station_networks
  has_many :spotifies
  has_many :unexts
  has_many :apple_musics
  has_many :d_anime_stores
  has_many :au_video_passes
  has_many :d_tvs
  has_many :fods
  has_many :line_musics
  has_many :netflixes
  has_many :you_tube_premia
end

app/models/you_tube_premium.rb
# frozen_string_literal: true

class YouTubePremium < ApplicationRecord
  validates :price, presence: true
  belongs_to :user
end

app/controllers/fo_ds_controller.rb
# frozen_string_literal: true

class FoDsController < ApplicationController
  before_action :set_fod, only: %i[show edit update destroy]

  # GET /fods
  # GET /fods.json
  def index
    @fods = Fod.all
  end

  # GET /fods/1
  # GET /fods/1.json
  def show; end

  # GET /fods/new
  def new
    @fod = Fod.new
  end

  # GET /fods/1/edit
  def edit; end

  # POST /fods
  # POST /fods.json
  def create
    @fod = Fod.new(fod_params)

    respond_to do |format|
      if @fod.save
        format.html { redirect_to @fod, notice: 'Fod was successfully created.' }
        format.json { render :show, status: :created, location: @fod }
      else
        format.html { render :new }
        format.json { render json: @fod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fods/1
  # PATCH/PUT /fods/1.json
  def update
    respond_to do |format|
      if @fod.update(fod_params)
        format.html { redirect_to @fod, notice: 'Fod was successfully updated.' }
        format.json { render :show, status: :ok, location: @fod }
      else
        format.html { render :edit }
        format.json { render json: @fod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fods/1
  # DELETE /fods/1.json
  def destroy
    @fod.destroy
    respond_to do |format|
      format.html { redirect_to fods_url, notice: 'Fod was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_fod
    @fod = Fod.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def fod_params
    params.require(:fod).permit(:price, :date, :update_period, :status, :memo, :user_id)
  end
end

app/controllers/fods_controller.rb
# frozen_string_literal: true

class FodsController < ApplicationController
  before_action :set_fod, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /fods
  # GET /fods.json
  def index
    @fods = Fod.all
  end

  # GET /fods/1
  # GET /fods/1.json
  def show; end

  # GET /fods/new
  def new
    @fod = current_user.fods.build
  end

  # GET /fods/1/edit
  def edit; end

  # POST /fods
  # POST /fods.json
  def create
    @fod = current_user.fods.build(fod_params)

    respond_to do |format|
      if @fod.save
        format.html { redirect_to root_path, notice: success('FOD') }
        format.json { render :show, status: :created, location: @fod }
      else
        format.html { render :new }
        format.json { render json: @fod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fods/1
  # PATCH/PUT /fods/1.json
  def update
    respond_to do |format|
      if @fod.update(fod_params)
        format.html { redirect_to root_path, notice: update('FOD') }
        format.json { render :show, status: :ok, location: @fod }
      else
        format.html { render :edit }
        format.json { render json: @fod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fods/1
  # DELETE /fods/1.json
  def destroy
    @fod.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: delete('FOD') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_fod
    @fod = Fod.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def fod_params
    params.require(:fod).permit(:price, :date, :update_period, :status, :memo, :user_id)
  end
end

app/helpers/amazons_helper.rb
# frozen_string_literal: true

module AmazonsHelper
end

app/helpers/d_t_vs_helper.rb
# frozen_string_literal: true

module DTVsHelper
end

app/helpers/fo_ds_helper.rb
# frozen_string_literal: true

module FoDsHelper
end

app/helpers/googoles_helper.rb
# frozen_string_literal: true

module GoogolesHelper
end

app/helpers/hulus_helper.rb
# frozen_string_literal: true

module HulusHelper
end

app/helpers/netflixes_helper.rb
# frozen_string_literal: true

module NetflixesHelper
end

app/helpers/top_helper.rb
# frozen_string_literal: true

module TopHelper
end

app/helpers/unexts_helper.rb
# frozen_string_literal: true

module UnextsHelper
end

app/views/fods/_form.html.erb
<%= form_with(model: fod, local: true) do |form| %>
  <% if fod.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fod.errors.count, "error") %> prohibited this fod from being saved:</h2>

      <ul>
      <% fod.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :update_period %>
    <%= form.number_field :update_period %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_area :memo %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fods/edit.html.erb
<h1>Editing Fod</h1>

<%= render 'form', fod: @fod %>

<%= link_to 'Show', @fod %> |
<%= link_to 'Back', fods_path %>

app/views/fods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fods</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Date</th>
      <th>Update period</th>
      <th>Status</th>
      <th>Memo</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fods.each do |fod| %>
      <tr>
        <td><%= fod.price %></td>
        <td><%= fod.date %></td>
        <td><%= fod.update_period %></td>
        <td><%= fod.status %></td>
        <td><%= fod.memo %></td>
        <td><%= fod.user_id %></td>
        <td><%= link_to 'Show', fod %></td>
        <td><%= link_to 'Edit', edit_fod_path(fod) %></td>
        <td><%= link_to 'Destroy', fod, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fod', new_fod_path %>

app/views/fods/new.html.erb
<h1>Fod</h1>
<%= render 'layouts/alert', service: @fod %>
<%= render 'layouts/form', service: @fod %>

app/views/fods/show.html.erb
<%= render 'layouts/show', name: 'FOD', url: @fod %>